### ISSUE TITLE
工程下载后编译失败

### ISSUE THREAD

**Issue by zfm96** [siren-ocean/SystemUI#1]
用最新版AS导入工程后编译，出现res资源中字符串重复的错误。
Found item String/power_remaining_duration_only_shutdown_imminent more than one time
![Uploading 截屏2022-12-05 16.13.57.png…]()

**Comment by siren-ocean** [comment]
你看下执行步骤，第一步运行在Filter上的主函数，执行过滤任务，可以把资源重复的字符串去掉，然后你再试试看！
毕竟SystemUI是一个系统应用，有一些特殊配置Android Studio不能识别，会导致编译失败。
