### ISSUE TITLE
工程可以顺利编译，但是在Android Studio中预览代码还是存在红线

### ISSUE THREAD

**Issue by ZhaoSiBo** [siren-ocean/SystemUI#2]
目前已经顺利编译出项目，产出apk，不过目前遇到的问题是在Android Studio中预览代码还是存在红线，既As在找代码的时候还是会去默认的android.jar中寻找被隐藏的api，没有找我们引入的framework.jar，请问下，作者也存在同样的情况吗？是否有情况规避呢？
![image](https://user-images.githubusercontent.com/22452283/222316895-1f914e66-057b-4644-8c89-2da411c7d076.png)

**Comment by ZhaoSiBo** [comment]
找到办法了，在站内找到了如何自己生成一个没有系统限制api jar包的方法
https://github.com/JetpackDuba/android-jar-with-hidden-api

**Comment by siren-ocean** [comment]
good
